### ISSUE TITLE
(Request) RemoteID Sniffing and Decoding Bluetooth 

### ISSUE THREAD

**Issue by alphafox02** [ElectronicCats/CatSniffer#72]
I think perhaps decoding RemoteID per the most recent standard required on US/Europe drones would be handy if accomplished by CatSniffer. 

I was reading over this link,
https://github.com/opendroneid/opendroneid-core-c?tab=readme-ov-file

And this caught my attention under this section 
https://github.com/opendroneid/opendroneid-core-c?tab=readme-ov-file#bluetooth-sniffing

“ Using Texas Instruments Bluetooth boards, it should be possible to use this SW to pick up all Bluetooth advertisements from a transmitter: https://github.com/nccgroup/Sniffle “

It may just be a matter of using CatSniffer, Sniffle, and the Wireshark dissectors from the link above. I see CatSniffer is up to what appears to be 1.7 Sniffle and I recall in the past being able to get the Wireshark Sniffle connection working.

**Comment by alphafox02** [comment]
WiFi RemoteID decoding would be great too. I just realized all the repositories are split up with software being separate from this repo. Assuming software requests should move there.

**Comment by alphafox02** [comment]
I’ve pulled in those to my Wireshark to combine with Sniffle extcap Wireshark + CatSniffer, but I need to setup RemoteID (open droneid) transmissions to test decoding. It’ll be nice if one day possible to do everything in one native with the CatSniffer sniffer tool. One step at a time though. :) 

https://github.com/opendroneid/wireshark-dissector

**Comment by Marcelol52** [comment]
Hi Alphafox02. Thank you for sharing this request with us. We always appreciate you guys bringing to our attention exciting things like this. 

Indeed, we have separated the CatSniffer project in three different repositories, this was done in order to have a better control on releases for the board. The main [CatSniffer](https://github.com/ElectronicCats/CatSniffer) repository will be kept for the Hardware, and we have made two new repositories for [CatSniffer Tools](https://github.com/ElectronicCats/CatSniffer-Tools) and [CatSniffer Firmware](https://github.com/ElectronicCats/CatSniffer-Firmware).

You are correct, we do have compatibility with Sniffle and Wireshark, we have a [tutorial ](https://github.com/ElectronicCats/CatSniffer/wiki/06.-Supported-Software#using-sniffle-with-wireshark)on our WiKi on how to get them working. Also, if you are able to get it working, share your progress with us. We appreciate all contributions.

**Comment by sabas1080** [comment]
Hi This feature will be performed by @JahazielLem coming soon

**Comment by alphafox02** [comment]
Thanks for the follow ups! I plan to order a known legitimate RemoteID transmitter and test this open source opendroneID repo against it just to see if I can get decodings. My understanding is open droneid and remoteID are the same thing, so I assume since it sounds like the standards are public and if vendors follow them, the code above should hopefully work.

**Comment by alphafox02** [comment]
I thought perhaps this would also be a good reference as it seems to be verified working to some extend with bluetooth and detecting both legacy bt4 but also bt5 long range and some other features or so it sounds like.

https://github.com/dronetag/drone-scanner

Details on the bluetooth capabilities 
https://github.com/dronetag/drone-scanner/blob/master/docs/features.md

**Comment by alphafox02** [comment]
Please have a peek here, seems promising. 

https://github.com/nccgroup/Sniffle/issues/74
